name = "crypto-donate"
main = "src/worker.tsx"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DOMAIN = "crypto-donate.insidexofficial.workers.dev"

[[kv_namespaces]]
binding = "KV"
id = "e46f47ffb9e94424ad698c91276efd34"
